CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_02_groupE_no_match_fold0 --data_path ../data/1017_splits/task_AF/cell_month_02/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_02/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 0 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_02_groupE_no_match_fold1 --data_path ../data/1017_splits/task_AF/cell_month_02/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_02/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 1 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_02_groupE_no_match_fold2 --data_path ../data/1017_splits/task_AF/cell_month_02/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_02/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 2 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_02_groupE_no_match_fold3 --data_path ../data/1017_splits/task_AF/cell_month_02/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_02/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 3 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_02_groupE_no_match_fold4 --data_path ../data/1017_splits/task_AF/cell_month_02/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_02/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 4 --inference_only --batch_size 1

CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_04_groupE_no_match_fold0 --data_path ../data/1017_splits/task_AF/cell_month_04/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_04/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 0 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_04_groupE_no_match_fold1 --data_path ../data/1017_splits/task_AF/cell_month_04/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_04/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 1 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_04_groupE_no_match_fold2 --data_path ../data/1017_splits/task_AF/cell_month_04/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_04/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 2 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_04_groupE_no_match_fold3 --data_path ../data/1017_splits/task_AF/cell_month_04/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_04/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 3 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_04_groupE_no_match_fold4 --data_path ../data/1017_splits/task_AF/cell_month_04/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_04/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 4 --inference_only --batch_size 1

CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_06_groupE_no_match_fold0 --data_path ../data/1017_splits/task_AF/cell_month_06/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_06/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 0 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_06_groupE_no_match_fold1 --data_path ../data/1017_splits/task_AF/cell_month_06/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_06/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 1 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_06_groupE_no_match_fold2 --data_path ../data/1017_splits/task_AF/cell_month_06/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_06/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 2 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_06_groupE_no_match_fold3 --data_path ../data/1017_splits/task_AF/cell_month_06/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_06/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 3 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_06_groupE_no_match_fold4 --data_path ../data/1017_splits/task_AF/cell_month_06/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_06/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 4 --inference_only --batch_size 1

CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_08_groupE_no_match_fold0 --data_path ../data/1017_splits/task_AF/cell_month_08/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_08/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 0 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_08_groupE_no_match_fold1 --data_path ../data/1017_splits/task_AF/cell_month_08/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_08/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 1 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_08_groupE_no_match_fold2 --data_path ../data/1017_splits/task_AF/cell_month_08/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_08/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 2 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_08_groupE_no_match_fold3 --data_path ../data/1017_splits/task_AF/cell_month_08/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_08/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 3 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_08_groupE_no_match_fold4 --data_path ../data/1017_splits/task_AF/cell_month_08/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_08/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 4 --inference_only --batch_size 1

CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_10_groupE_no_match_fold0 --data_path ../data/1017_splits/task_AF/cell_month_10/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_10/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 0 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_10_groupE_no_match_fold1 --data_path ../data/1017_splits/task_AF/cell_month_10/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_10/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 1 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_10_groupE_no_match_fold2 --data_path ../data/1017_splits/task_AF/cell_month_10/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_10/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 2 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_10_groupE_no_match_fold3 --data_path ../data/1017_splits/task_AF/cell_month_10/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_10/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 3 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_10_groupE_no_match_fold4 --data_path ../data/1017_splits/task_AF/cell_month_10/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_10/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 4 --inference_only --batch_size 1

CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_14_groupE_no_match_fold0 --data_path ../data/1017_splits/task_AF/cell_month_14/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_14/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 0 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_14_groupE_no_match_fold1 --data_path ../data/1017_splits/task_AF/cell_month_14/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_14/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 1 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_14_groupE_no_match_fold2 --data_path ../data/1017_splits/task_AF/cell_month_14/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_14/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 2 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_14_groupE_no_match_fold3 --data_path ../data/1017_splits/task_AF/cell_month_14/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_14/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 3 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_14_groupE_no_match_fold4 --data_path ../data/1017_splits/task_AF/cell_month_14/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_14/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 4 --inference_only --batch_size 1

CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_16_groupE_no_match_fold0 --data_path ../data/1017_splits/task_AF/cell_month_16/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_16/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 0 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_16_groupE_no_match_fold1 --data_path ../data/1017_splits/task_AF/cell_month_16/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_16/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 1 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_16_groupE_no_match_fold2 --data_path ../data/1017_splits/task_AF/cell_month_16/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_16/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 2 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_16_groupE_no_match_fold3 --data_path ../data/1017_splits/task_AF/cell_month_16/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_16/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 3 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_16_groupE_no_match_fold4 --data_path ../data/1017_splits/task_AF/cell_month_16/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_16/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 4 --inference_only --batch_size 1

CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_18_groupE_no_match_fold0 --data_path ../data/1017_splits/task_AF/cell_month_18/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_18/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 0 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_18_groupE_no_match_fold1 --data_path ../data/1017_splits/task_AF/cell_month_18/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_18/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 1 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_18_groupE_no_match_fold2 --data_path ../data/1017_splits/task_AF/cell_month_18/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_18/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 2 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_18_groupE_no_match_fold3 --data_path ../data/1017_splits/task_AF/cell_month_18/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_18/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 3 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_AF_month_18_groupE_no_match_fold4 --data_path ../data/1017_splits/task_AF/cell_month_18/input_data_no_matching/ --patient_csv ../data/1017_splits/task_AF/cell_month_18/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 4 --inference_only --batch_size 1

CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_04_groupE_no_match_fold0 --data_path ../data/1017_splits/task_D/cell_month_04/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_04/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 0 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_04_groupE_no_match_fold1 --data_path ../data/1017_splits/task_D/cell_month_04/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_04/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 1 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_04_groupE_no_match_fold2 --data_path ../data/1017_splits/task_D/cell_month_04/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_04/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 2 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_04_groupE_no_match_fold3 --data_path ../data/1017_splits/task_D/cell_month_04/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_04/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 3 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_04_groupE_no_match_fold4 --data_path ../data/1017_splits/task_D/cell_month_04/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_04/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 4 --inference_only --batch_size 1

CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_06_groupE_no_match_fold0 --data_path ../data/1017_splits/task_D/cell_month_06/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_06/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 0 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_06_groupE_no_match_fold1 --data_path ../data/1017_splits/task_D/cell_month_06/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_06/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 1 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_06_groupE_no_match_fold2 --data_path ../data/1017_splits/task_D/cell_month_06/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_06/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 2 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_06_groupE_no_match_fold3 --data_path ../data/1017_splits/task_D/cell_month_06/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_06/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 3 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_06_groupE_no_match_fold4 --data_path ../data/1017_splits/task_D/cell_month_06/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_06/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 4 --inference_only --batch_size 1

CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_08_groupE_no_match_fold0 --data_path ../data/1017_splits/task_D/cell_month_08/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_08/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 0 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_08_groupE_no_match_fold1 --data_path ../data/1017_splits/task_D/cell_month_08/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_08/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 1 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_08_groupE_no_match_fold2 --data_path ../data/1017_splits/task_D/cell_month_08/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_08/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 2 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_08_groupE_no_match_fold3 --data_path ../data/1017_splits/task_D/cell_month_08/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_08/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 3 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_08_groupE_no_match_fold4 --data_path ../data/1017_splits/task_D/cell_month_08/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_08/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 4 --inference_only --batch_size 1

CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_10_groupE_no_match_fold0 --data_path ../data/1017_splits/task_D/cell_month_10/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_10/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 0 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_10_groupE_no_match_fold1 --data_path ../data/1017_splits/task_D/cell_month_10/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_10/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 1 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_10_groupE_no_match_fold2 --data_path ../data/1017_splits/task_D/cell_month_10/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_10/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 2 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_10_groupE_no_match_fold3 --data_path ../data/1017_splits/task_D/cell_month_10/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_10/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 3 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_10_groupE_no_match_fold4 --data_path ../data/1017_splits/task_D/cell_month_10/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_10/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 4 --inference_only --batch_size 1

CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_12_groupE_no_match_fold0 --data_path ../data/1017_splits/task_D/cell_month_12/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_12/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 0 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_12_groupE_no_match_fold1 --data_path ../data/1017_splits/task_D/cell_month_12/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_12/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 1 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_12_groupE_no_match_fold2 --data_path ../data/1017_splits/task_D/cell_month_12/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_12/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 2 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_12_groupE_no_match_fold3 --data_path ../data/1017_splits/task_D/cell_month_12/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_12/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 3 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_12_groupE_no_match_fold4 --data_path ../data/1017_splits/task_D/cell_month_12/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_12/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 4 --inference_only --batch_size 1

CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_14_groupE_no_match_fold0 --data_path ../data/1017_splits/task_D/cell_month_14/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_14/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 0 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_14_groupE_no_match_fold1 --data_path ../data/1017_splits/task_D/cell_month_14/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_14/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 1 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_14_groupE_no_match_fold2 --data_path ../data/1017_splits/task_D/cell_month_14/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_14/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 2 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_14_groupE_no_match_fold3 --data_path ../data/1017_splits/task_D/cell_month_14/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_14/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 3 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_14_groupE_no_match_fold4 --data_path ../data/1017_splits/task_D/cell_month_14/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_14/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 4 --inference_only --batch_size 1

CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_16_groupE_no_match_fold0 --data_path ../data/1017_splits/task_D/cell_month_16/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_16/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 0 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_16_groupE_no_match_fold1 --data_path ../data/1017_splits/task_D/cell_month_16/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_16/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 1 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_16_groupE_no_match_fold2 --data_path ../data/1017_splits/task_D/cell_month_16/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_16/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 2 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_16_groupE_no_match_fold3 --data_path ../data/1017_splits/task_D/cell_month_16/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_16/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 3 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_16_groupE_no_match_fold4 --data_path ../data/1017_splits/task_D/cell_month_16/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_16/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 4 --inference_only --batch_size 1

CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_18_groupE_no_match_fold0 --data_path ../data/1017_splits/task_D/cell_month_18/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_18/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 0 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_18_groupE_no_match_fold1 --data_path ../data/1017_splits/task_D/cell_month_18/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_18/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 1 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_18_groupE_no_match_fold2 --data_path ../data/1017_splits/task_D/cell_month_18/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_18/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 2 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_18_groupE_no_match_fold3 --data_path ../data/1017_splits/task_D/cell_month_18/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_18/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 3 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_D_month_18_groupE_no_match_fold4 --data_path ../data/1017_splits/task_D/cell_month_18/input_data_no_matching/ --patient_csv ../data/1017_splits/task_D/cell_month_18/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 4 --inference_only --batch_size 1

CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_G_month_10_groupE_no_match_fold0 --data_path ../data/1017_splits/task_G/cell_month_10/input_data_no_matching/ --patient_csv ../data/1017_splits/task_G/cell_month_10/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 0 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_G_month_10_groupE_no_match_fold1 --data_path ../data/1017_splits/task_G/cell_month_10/input_data_no_matching/ --patient_csv ../data/1017_splits/task_G/cell_month_10/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 1 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_G_month_10_groupE_no_match_fold2 --data_path ../data/1017_splits/task_G/cell_month_10/input_data_no_matching/ --patient_csv ../data/1017_splits/task_G/cell_month_10/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 2 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_G_month_10_groupE_no_match_fold3 --data_path ../data/1017_splits/task_G/cell_month_10/input_data_no_matching/ --patient_csv ../data/1017_splits/task_G/cell_month_10/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 3 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_G_month_10_groupE_no_match_fold4 --data_path ../data/1017_splits/task_G/cell_month_10/input_data_no_matching/ --patient_csv ../data/1017_splits/task_G/cell_month_10/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 4 --inference_only --batch_size 1

CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_G_month_12_groupE_no_match_fold0 --data_path ../data/1017_splits/task_G/cell_month_12/input_data_no_matching/ --patient_csv ../data/1017_splits/task_G/cell_month_12/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 0 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_G_month_12_groupE_no_match_fold1 --data_path ../data/1017_splits/task_G/cell_month_12/input_data_no_matching/ --patient_csv ../data/1017_splits/task_G/cell_month_12/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 1 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_G_month_12_groupE_no_match_fold2 --data_path ../data/1017_splits/task_G/cell_month_12/input_data_no_matching/ --patient_csv ../data/1017_splits/task_G/cell_month_12/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 2 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_G_month_12_groupE_no_match_fold3 --data_path ../data/1017_splits/task_G/cell_month_12/input_data_no_matching/ --patient_csv ../data/1017_splits/task_G/cell_month_12/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 3 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_G_month_12_groupE_no_match_fold4 --data_path ../data/1017_splits/task_G/cell_month_12/input_data_no_matching/ --patient_csv ../data/1017_splits/task_G/cell_month_12/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 4 --inference_only --batch_size 1

CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_G_month_14_groupE_no_match_fold0 --data_path ../data/1017_splits/task_G/cell_month_14/input_data_no_matching/ --patient_csv ../data/1017_splits/task_G/cell_month_14/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 0 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_G_month_14_groupE_no_match_fold1 --data_path ../data/1017_splits/task_G/cell_month_14/input_data_no_matching/ --patient_csv ../data/1017_splits/task_G/cell_month_14/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 1 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_G_month_14_groupE_no_match_fold2 --data_path ../data/1017_splits/task_G/cell_month_14/input_data_no_matching/ --patient_csv ../data/1017_splits/task_G/cell_month_14/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 2 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_G_month_14_groupE_no_match_fold3 --data_path ../data/1017_splits/task_G/cell_month_14/input_data_no_matching/ --patient_csv ../data/1017_splits/task_G/cell_month_14/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 3 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_G_month_14_groupE_no_match_fold4 --data_path ../data/1017_splits/task_G/cell_month_14/input_data_no_matching/ --patient_csv ../data/1017_splits/task_G/cell_month_14/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 4 --inference_only --batch_size 1

CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_G_month_16_groupE_no_match_fold0 --data_path ../data/1017_splits/task_G/cell_month_16/input_data_no_matching/ --patient_csv ../data/1017_splits/task_G/cell_month_16/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 0 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_G_month_16_groupE_no_match_fold1 --data_path ../data/1017_splits/task_G/cell_month_16/input_data_no_matching/ --patient_csv ../data/1017_splits/task_G/cell_month_16/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 1 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_G_month_16_groupE_no_match_fold2 --data_path ../data/1017_splits/task_G/cell_month_16/input_data_no_matching/ --patient_csv ../data/1017_splits/task_G/cell_month_16/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 2 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_G_month_16_groupE_no_match_fold3 --data_path ../data/1017_splits/task_G/cell_month_16/input_data_no_matching/ --patient_csv ../data/1017_splits/task_G/cell_month_16/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 3 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_G_month_16_groupE_no_match_fold4 --data_path ../data/1017_splits/task_G/cell_month_16/input_data_no_matching/ --patient_csv ../data/1017_splits/task_G/cell_month_16/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 4 --inference_only --batch_size 1

CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_G_month_18_groupE_no_match_fold0 --data_path ../data/1017_splits/task_G/cell_month_18/input_data_no_matching/ --patient_csv ../data/1017_splits/task_G/cell_month_18/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 0 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_G_month_18_groupE_no_match_fold1 --data_path ../data/1017_splits/task_G/cell_month_18/input_data_no_matching/ --patient_csv ../data/1017_splits/task_G/cell_month_18/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 1 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_G_month_18_groupE_no_match_fold2 --data_path ../data/1017_splits/task_G/cell_month_18/input_data_no_matching/ --patient_csv ../data/1017_splits/task_G/cell_month_18/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 2 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_G_month_18_groupE_no_match_fold3 --data_path ../data/1017_splits/task_G/cell_month_18/input_data_no_matching/ --patient_csv ../data/1017_splits/task_G/cell_month_18/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 3 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_G_month_18_groupE_no_match_fold4 --data_path ../data/1017_splits/task_G/cell_month_18/input_data_no_matching/ --patient_csv ../data/1017_splits/task_G/cell_month_18/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 4 --inference_only --batch_size 1


CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_H_month_10_groupE_no_match_fold0 --data_path ../data/1017_splits/task_H/cell_month_10/input_data_no_matching/ --patient_csv ../data/1017_splits/task_H/cell_month_10/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 0 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_H_month_10_groupE_no_match_fold1 --data_path ../data/1017_splits/task_H/cell_month_10/input_data_no_matching/ --patient_csv ../data/1017_splits/task_H/cell_month_10/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 1 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_H_month_10_groupE_no_match_fold2 --data_path ../data/1017_splits/task_H/cell_month_10/input_data_no_matching/ --patient_csv ../data/1017_splits/task_H/cell_month_10/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 2 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_H_month_10_groupE_no_match_fold3 --data_path ../data/1017_splits/task_H/cell_month_10/input_data_no_matching/ --patient_csv ../data/1017_splits/task_H/cell_month_10/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 3 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_H_month_10_groupE_no_match_fold4 --data_path ../data/1017_splits/task_H/cell_month_10/input_data_no_matching/ --patient_csv ../data/1017_splits/task_H/cell_month_10/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 4 --inference_only --batch_size 1

CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_H_month_12_groupE_no_match_fold0 --data_path ../data/1017_splits/task_H/cell_month_12/input_data_no_matching/ --patient_csv ../data/1017_splits/task_H/cell_month_12/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 0 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_H_month_12_groupE_no_match_fold1 --data_path ../data/1017_splits/task_H/cell_month_12/input_data_no_matching/ --patient_csv ../data/1017_splits/task_H/cell_month_12/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 1 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_H_month_12_groupE_no_match_fold2 --data_path ../data/1017_splits/task_H/cell_month_12/input_data_no_matching/ --patient_csv ../data/1017_splits/task_H/cell_month_12/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 2 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_H_month_12_groupE_no_match_fold3 --data_path ../data/1017_splits/task_H/cell_month_12/input_data_no_matching/ --patient_csv ../data/1017_splits/task_H/cell_month_12/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 3 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_H_month_12_groupE_no_match_fold4 --data_path ../data/1017_splits/task_H/cell_month_12/input_data_no_matching/ --patient_csv ../data/1017_splits/task_H/cell_month_12/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 4 --inference_only --batch_size 1

CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_H_month_14_groupE_no_match_fold0 --data_path ../data/1017_splits/task_H/cell_month_14/input_data_no_matching/ --patient_csv ../data/1017_splits/task_H/cell_month_14/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 0 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_H_month_14_groupE_no_match_fold1 --data_path ../data/1017_splits/task_H/cell_month_14/input_data_no_matching/ --patient_csv ../data/1017_splits/task_H/cell_month_14/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 1 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_H_month_14_groupE_no_match_fold2 --data_path ../data/1017_splits/task_H/cell_month_14/input_data_no_matching/ --patient_csv ../data/1017_splits/task_H/cell_month_14/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 2 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_H_month_14_groupE_no_match_fold3 --data_path ../data/1017_splits/task_H/cell_month_14/input_data_no_matching/ --patient_csv ../data/1017_splits/task_H/cell_month_14/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 3 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_H_month_14_groupE_no_match_fold4 --data_path ../data/1017_splits/task_H/cell_month_14/input_data_no_matching/ --patient_csv ../data/1017_splits/task_H/cell_month_14/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 4 --inference_only --batch_size 1

CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_H_month_16_groupE_no_match_fold0 --data_path ../data/1017_splits/task_H/cell_month_16/input_data_no_matching/ --patient_csv ../data/1017_splits/task_H/cell_month_16/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 0 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_H_month_16_groupE_no_match_fold1 --data_path ../data/1017_splits/task_H/cell_month_16/input_data_no_matching/ --patient_csv ../data/1017_splits/task_H/cell_month_16/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 1 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_H_month_16_groupE_no_match_fold2 --data_path ../data/1017_splits/task_H/cell_month_16/input_data_no_matching/ --patient_csv ../data/1017_splits/task_H/cell_month_16/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 2 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_H_month_16_groupE_no_match_fold3 --data_path ../data/1017_splits/task_H/cell_month_16/input_data_no_matching/ --patient_csv ../data/1017_splits/task_H/cell_month_16/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 3 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_H_month_16_groupE_no_match_fold4 --data_path ../data/1017_splits/task_H/cell_month_16/input_data_no_matching/ --patient_csv ../data/1017_splits/task_H/cell_month_16/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 4 --inference_only --batch_size 1


CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_I_month_12_groupE_no_match_fold0 --data_path ../data/1017_splits/task_I/cell_month_12/input_data_no_matching/ --patient_csv ../data/1017_splits/task_I/cell_month_12/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 0 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_I_month_12_groupE_no_match_fold1 --data_path ../data/1017_splits/task_I/cell_month_12/input_data_no_matching/ --patient_csv ../data/1017_splits/task_I/cell_month_12/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 1 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_I_month_12_groupE_no_match_fold2 --data_path ../data/1017_splits/task_I/cell_month_12/input_data_no_matching/ --patient_csv ../data/1017_splits/task_I/cell_month_12/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 2 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_I_month_12_groupE_no_match_fold3 --data_path ../data/1017_splits/task_I/cell_month_12/input_data_no_matching/ --patient_csv ../data/1017_splits/task_I/cell_month_12/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 3 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_I_month_12_groupE_no_match_fold4 --data_path ../data/1017_splits/task_I/cell_month_12/input_data_no_matching/ --patient_csv ../data/1017_splits/task_I/cell_month_12/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 4 --inference_only --batch_size 1

CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_I_month_14_groupE_no_match_fold0 --data_path ../data/1017_splits/task_I/cell_month_14/input_data_no_matching/ --patient_csv ../data/1017_splits/task_I/cell_month_14/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 0 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_I_month_14_groupE_no_match_fold1 --data_path ../data/1017_splits/task_I/cell_month_14/input_data_no_matching/ --patient_csv ../data/1017_splits/task_I/cell_month_14/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 1 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_I_month_14_groupE_no_match_fold2 --data_path ../data/1017_splits/task_I/cell_month_14/input_data_no_matching/ --patient_csv ../data/1017_splits/task_I/cell_month_14/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 2 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_I_month_14_groupE_no_match_fold3 --data_path ../data/1017_splits/task_I/cell_month_14/input_data_no_matching/ --patient_csv ../data/1017_splits/task_I/cell_month_14/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 3 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_I_month_14_groupE_no_match_fold4 --data_path ../data/1017_splits/task_I/cell_month_14/input_data_no_matching/ --patient_csv ../data/1017_splits/task_I/cell_month_14/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 4 --inference_only --batch_size 1

CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_I_month_16_groupE_no_match_fold0 --data_path ../data/1017_splits/task_I/cell_month_16/input_data_no_matching/ --patient_csv ../data/1017_splits/task_I/cell_month_16/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 0 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_I_month_16_groupE_no_match_fold1 --data_path ../data/1017_splits/task_I/cell_month_16/input_data_no_matching/ --patient_csv ../data/1017_splits/task_I/cell_month_16/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 1 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_I_month_16_groupE_no_match_fold2 --data_path ../data/1017_splits/task_I/cell_month_16/input_data_no_matching/ --patient_csv ../data/1017_splits/task_I/cell_month_16/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 2 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_I_month_16_groupE_no_match_fold3 --data_path ../data/1017_splits/task_I/cell_month_16/input_data_no_matching/ --patient_csv ../data/1017_splits/task_I/cell_month_16/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 3 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_I_month_16_groupE_no_match_fold4 --data_path ../data/1017_splits/task_I/cell_month_16/input_data_no_matching/ --patient_csv ../data/1017_splits/task_I/cell_month_16/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 4 --inference_only --batch_size 1

CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_I_month_18_groupE_no_match_fold0 --data_path ../data/1017_splits/task_I/cell_month_18/input_data_no_matching/ --patient_csv ../data/1017_splits/task_I/cell_month_18/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 0 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_I_month_18_groupE_no_match_fold1 --data_path ../data/1017_splits/task_I/cell_month_18/input_data_no_matching/ --patient_csv ../data/1017_splits/task_I/cell_month_18/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 1 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_I_month_18_groupE_no_match_fold2 --data_path ../data/1017_splits/task_I/cell_month_18/input_data_no_matching/ --patient_csv ../data/1017_splits/task_I/cell_month_18/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 2 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_I_month_18_groupE_no_match_fold3 --data_path ../data/1017_splits/task_I/cell_month_18/input_data_no_matching/ --patient_csv ../data/1017_splits/task_I/cell_month_18/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 3 --inference_only --batch_size 1
CUDA_VISIBLE_DEVICES=1 python3 main_case.py --exp_name task_I_month_18_groupE_no_match_fold4 --data_path ../data/1017_splits/task_I/cell_month_18/input_data_no_matching/ --patient_csv ../data/1017_splits/task_I/cell_month_18/input_label.csv --modal rgb --num_segments 30 --num_clusters 5 --num_epochs 300 --detection_inf_step 20 --fold 4 --inference_only --batch_size 1
